### ISSUE TITLE
Why drawing directly with Graphics API?

### ISSUE THREAD

**Issue by xvnnnk** [Fy-/FyWorld#1]
I was wandering around and I noticed that you don't use SpriteRenderer to render objects. Instead, you draw directly using Graphics.DrawInstanced. Is there a specific reason that you chose to do it this way?

**Comment by Fy-** [comment]
Hey, thanks for your interest in FyWorld. When I started this project I did a lot of tests with Unity, generating big maps, and SpriteRenderer was always slower, by a lot. It's not relevant when you zoom in because you display only a small portion of the world, but when you zoom out I want to be able to see at least half of the full map (and not just a texture, with plants, animals etc... moving and growing). So performance was the main reason, but I didn't check the latest unity updates to check if there is something better now.

**Comment by xvnnnk** [comment]
Thank you. It's all clear now. 
And yes. I created the account to ask this. lol.
